/**
 * Movie actions
 */
export const FETCH_MOVIES = "FETCH_MOVIES"
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE"
export const SEARCH_MOVIES = "SEARCH_MOVIES"
export const SEARCH_MOVIES_FAILURE = "SEARCH_MOVIES_FAILURE"
export const SEARCH_COUNTRIES = "SEARCH_COUNTRIES"
export const SEARCH_COUNTRIES_FAILURE = "SEARCH_COUNTRIES_FAILURE"
export const RECEIVED_COUNTRY_RESULTS = "RECEIVED_COUNTRY_RESULTS"
export const RECEIVED_MOVIES = "RECEIVED_MOVIES"
export const MOVIE_DETAIL = "MOVIE_DETAIL"
export const RECEIVED_SEARCH_RESULTS = "RECEIVED_SEARCH_RESULTS"
export const FETCH_MOVIE_BY_ID = "FETCH_MOVIE_BY_ID"
export const FETCH_MOVIE_BY_ID_FAILURE = "FETCH_MOVIE_BY_ID_FAILURE"
export const RECEIVED_MOVIE_BY_ID = "RECEIVED_MOVIE_BY_ID"
export const VIEW_MOVIE = "VIEW_MOVIE"
export const PAGINATE_MOVIES = "PAGINATE_MOVIES"
export const RECEIVED_PAGINATION = "RECEIVED_PAGINATION"
export const BEGIN_PAGING = "BEGIN_PAGING"
export const PROP_FACET_FILTER = "PROP_FACET_FILTER"
export const SUBMIT_COMMENT = "SUBMIT_COMMENT"
export const SUBMIT_COMMENT_SUCCESS = "SUBMIT_COMMENT_SUCCESS"
export const SUBMIT_COMMENT_FAIL = "SUBMIT_COMMENT_FAIL"
export const UPDATE_COMMENT = "UPDATE_COMMENT"
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS"
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL"
export const DELETE_COMMENT = "DELETE_COMMENT"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL"
export const CLEAR_ERROR = "CLEAR_ERROR"

/**
 * Report Actions
 */

export const FETCH_USER_REPORT = "FETCH_USER_REPORT"
export const RECEIVED_USER_REPORT_FAILURE = "RECEIVED_USER_REPORT_FAILURE"
export const RECEIVED_USER_REPORT_SUCCESS = "RECEIVED_USER_REPORT_SUCCESS"

/**
 * Miscellaneous actions
 */

export const TOGGLE_DRAWER = "TOGGLE_DRAWER"
export const NO_OP = "NO_OP"

/**
 * User actions
 */

export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"
export const UPDATE_PREFS = "UPDATE_PREFS"
export const SAVE_PREFS = "SAVE_PREFS"
export const SAVE_PREFS_SUCCESS = "SAVE_PREFS_SUCCESS"
export const SAVE_PREFS_FAIL = "SAVE_PREFS_FAIL"
export const CHECK_ADMIN = "CHECK_ADMIN"
export const CHECK_ADMIN_SUCCESS = "CHECK_ADMIN_SUCCESS"
export const CHECK_ADMIN_FAIL = "CHECK_ADMIN_FAIL"

/**
 * Validation Actions
 */
export const VALIDATING_TICKET = "VALIDATING_TICKET"

export const VALIDATE_CONNECTION = "VALIDATE_CONNECTION"
export const VALIDATE_CONNECTION_SUCCESS =
  "VALIDATE_CONNECTION_SUCCESS"
export const VALIDATE_CONNECTION_ERROR =
  "VALIDATE_CONNECTION_ERROR"

export const VALIDATE_PROJECTION = "VALIDATE_PROJECTION"
export const VALIDATE_PROJECTION_SUCCESS =
  "VALIDATE_PROJECTION_SUCCESS"
export const VALIDATE_PROJECTION_ERROR =
  "VALIDATE_PROJECTION_ERROR"

export const VALIDATE_TEXT_AND_SUBFIELD =
  "VALIDATE_TEXT_AND_SUBFIELD"
export const VALIDATE_TEXT_AND_SUBFIELD_SUCCESS =
  "VALIDATE_TEXT_AND_SUBFIELD_SUCCESS"
export const VALIDATE_TEXT_AND_SUBFIELD_ERROR =
  "VALIDATE_TEXT_AND_SUBFIELD_ERROR"

export const VALIDATE_PAGING = "VALIDATE_PAGING"
export const VALIDATE_PAGING_SUCCESS = "VALIDATE_PAGING_SUCCESS"
export const VALIDATE_PAGING_ERROR = "VALIDATE_PAGING_ERROR"

export const VALIDATE_FACETED_SEARCH = "VALIDATE_FACETED_SEARCH"
export const VALIDATE_FACETED_SEARCH_SUCCESS =
  "VALIDATE_FACETED_SEARCH_SUCCESS"
export const VALIDATE_FACETED_SEARCH_ERROR =
  "VALIDATE_FACETED_SEARCH_ERROR"

export const VALIDATE_USER_MANAGEMENT = "VALIDATE_USER_MANAGEMENT"
export const VALIDATE_USER_MANAGEMENT_SUCCESS =
  "VALIDATE_USER_MANAGEMENT_SUCCESS"
export const VALIDATE_USER_MANAGEMENT_ERROR =
  "VALIDATE_USER_MANAGEMENT_ERROR"

export const VALIDATE_USER_PREFERENCES =
  "VALIDATE_USER_PREFERENCES"
export const VALIDATE_USER_PREFERENCES_SUCCESS =
  "VALIDATE_USER_PREFERENCES_SUCCESS"
export const VALIDATE_USER_PREFERENCES_ERROR =
  "VALIDATE_USER_PREFERENCES_ERROR"

export const VALIDATE_GET_COMMENTS = "VALIDATE_GET_COMMENTS"
export const VALIDATE_GET_COMMENTS_SUCCESS =
  "VALIDATE_GET_COMMENTS_SUCCESS"
export const VALIDATE_GET_COMMENTS_ERROR =
  "VALIDATE_GET_COMMENTS_ERROR"

export const VALIDATE_CREATE_UPDATE_COMMENTS =
  "VALIDATE_CREATE_UPDATE_COMMENTS"
export const VALIDATE_CREATE_UPDATE_COMMENTS_SUCCESS =
  "VALIDATE_CREATE_UPDATE_COMMENTS_SUCCESS"
export const VALIDATE_CREATE_UPDATE_COMMENTS_ERROR =
  "VALIDATE_CREATE_UPDATE_COMMENTS_ERROR"

export const VALIDATE_DELETE_COMMENTS = "VALIDATE_DELETE_COMMENTS"
export const VALIDATE_DELETE_COMMENTS_SUCCESS =
  "VALIDATE_DELETE_COMMENTS_SUCCESS"
export const VALIDATE_DELETE_COMMENTS_ERROR =
  "VALIDATE_DELETE_COMMENTS_ERROR"

export const VALIDATE_USER_REPORT = "VALIDATE_USER_REPORT"
export const VALIDATE_USER_REPORT_SUCCESS =
  "VALIDATE_USER_REPORT_SUCCESS"
export const VALIDATE_USER_REPORT_ERROR =
  "VALIDATE_USER_REPORT_ERROR"

export const VALIDATE_MIGRATION = "VALIDATE_MIGRATION"
export const VALIDATE_MIGRATION_SUCCESS =
  "VALIDATE_MIGRATION_SUCCESS"
export const VALIDATE_MIGRATION_ERROR = "VALIDATE_MIGRATION_ERROR"

export const VALIDATE_CONNECTION_POOLING =
  "VALIDATE_CONNECTION_POOLING"
export const VALIDATE_CONNECTION_POOLING_SUCCESS =
  "VALIDATE_CONNECTION_POOLING_SUCCESS"
export const VALIDATE_CONNECTION_POOLING_ERROR =
  "VALIDATE_CONNECTION_POOLING_ERROR"

export const VALIDATE_TIMEOUTS = "VALIDATE_TIMEOUTS"
export const VALIDATE_TIMEOUTS_SUCCESS =
  "VALIDATE_TIMEOUTS_SUCCESS"
export const VALIDATE_TIMEOUTS_ERROR = "VALIDATE_TIMEOUTS_ERROR"

export const VALIDATE_ERROR_HANDLING = "VALIDATE_ERROR_HANDLING"
export const VALIDATE_ERROR_HANDLING_SUCCESS =
  "VALIDATE_ERROR_HANDLING_SUCCESS"
export const VALIDATE_ERROR_HANDLING_ERROR =
  "VALIDATE_ERROR_HANDLING_ERROR"

export const VALIDATE_POLP = "VALIDATE_POLP"
export const VALIDATE_POLP_SUCCESS = "VALIDATE_POLP_SUCCESS"
export const VALIDATE_POLP_ERROR = "VALIDATE_POLP_ERROR"
